# Dependabot configuration for automated dependency updates
# See: https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  # Enable version updates for Dart packages
  - package-ecosystem: "pub"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "Europe/Berlin"
    open-pull-requests-limit: 5
    reviewers:
      - "@me"
    assignees:
      - "@me"
    commit-message:
      prefix: "deps"
      prefix-development: "dev-deps"
    labels:
      - "dependencies"
      - "automated"
    allow:
      # Allow all dependency types
      - dependency-type: "direct"
      - dependency-type: "indirect"
    ignore:
      # Ignore major version updates for stable packages
      - dependency-name: "lints"
        update-types: ["version-update:semver-major"]
    groups:
      test-dependencies:
        patterns:
          - "test*"
          - "mockito*"
          - "build_runner*"

  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "10:00"
      timezone: "Europe/Berlin"
    open-pull-requests-limit: 3
    reviewers:
      - "@me"
    assignees:
      - "@me"
    commit-message:
      prefix: "ci"
    labels:
      - "github-actions"
      - "automated"
