name: swapi_cli
description: A CLI tool that displays random elements from the Star Wars API
version: 1.1.20

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  http: ^1.1.0
  args: ^2.4.2
  pubspec_parse: ^1.5.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.24.0
  mockito: ^5.4.2
  build_runner: ^2.4.7

executables:
  swapi: swapi_cli
