name: Update Homebrew Formula

on:
  release:
    types: [published]

jobs:
  update-homebrew:
    name: Update Homebrew Formula
    runs-on: ubuntu-latest
    
    steps:
      - name: Update Homebrew formula
        uses: mislav/bump-homebrew-formula-action@v2
        with:
          formula-name: swapi-cli
          formula-path: Formula/swapi-cli.rb
          homebrew-tap: dnl-jst/homebrew-tap
          download-url: "https://github.com/dnl-jst/swapi-cli/releases/download/${{ github.ref_name }}/swapi-cli-macos"
          commit-message: |
            Update swapi-cli to ${{ github.ref_name }}
            
            Automatically updated by GitHub Actions
        env:
          COMMITTER_TOKEN: ${{ secrets.HOMEBREW_TAP_TOKEN }}
